export const meta = {
  name: 'debonus',
  description: 'Remove "bonus" / "main entry" labels from published piece decks (all entries are equal), republish the changed slides',
  phases: [{ title: 'Fix', detail: 'one agent per deck' }],
}
const job = d => `The user asked earlier, verbatim: "in the main page pls dont put something like Main Entry all are equal entries reflect that". All 22 pieces of "What the Noise Remembers" are equal entries. In the slide files of this deck, remove every label or phrase that ranks pieces: "bonus", "bonus piece", "bonus entry", "(bonus)", "* bonus entry", "main entry", "pieces 12 to 22 are bonus pieces", "piece.json: bonus true", asterisks marking bonus entries, and similar. Rewrite each affected sentence so it still reads naturally and keeps its facts (e.g. "This is Chirp Instrument, our entry for Challenge 02, Make it audible"; "Quantum Lenia · 17"; "22 Scroll Unroll"). KEEP game-scoring uses of the word (e.g. "a time bonus" in a game's points rule). Do not change anything else.
Deck folder: ${d.root} (slides in ${d.root}\\project\\slides\\). Affected files (from a grep): ${d.files.join(', ')}; grep the folder again yourself (case-insensitive "bonus" and "main entr") in case of others. Edit the files with your file tools (keep each file exactly one <section> as now). Then publish ONLY the changed files in ONE Artifact call: publish with url=${d.url}, root=${d.root}, file_path=<absolute path of one changed file>, files={"project/slides/<id>.html":"project/slides/<id>.html" for the other changed files}. If the publish is refused because the deck changed, read what the refusal names, redo your edit on the latest version of those files, and publish again. Return the changed file names.`
const OUT = {type:'object', properties:{changed:{type:'array', items:{type:'string'}}, ok:{type:'boolean'}}, required:['changed','ok']}
return await parallel(args.decks.map(d => () => agent(job(d), {label:`debonus:${d.n}`, phase:'Fix', schema: OUT, effort:'low'}).then(r => ({n: d.n, r}))))
