export const meta = {
  name: 'decks-all',
  description: 'For each challenge: set up a Slides deck (images, index, cover), write its slides in parallel, publish them',
  phases: [
    { title: 'Setup', detail: 'create deck, upload images, index + cover, slide briefs' },
    { title: 'Write', detail: 'parallel slide writers per deck' },
    { title: 'Publish', detail: 'publish all slide files' },
  ],
}
const ROOT = 'C:\\Users\\Rahma\\OneDrive\\Desktop\\MOTH QUANTUM'
const SCR = args.scratch
const SLIDES_TYPE = 'https://claude.ai/artifact/8jTsAFQMFDb2oA8MsPJ2eL'
const COVER = `${SCR}\\decks\\c01\\project\\slides\\cover.html`
const SITE = 'https://hrahman12.github.io/What-the-noise-remembers-MOTH-QUANTUM-HACK/'
const REPO = 'https://github.com/hrahman12/What-the-noise-remembers-MOTH-QUANTUM-HACK'
const ASK = `CONTEXT: the user asked, verbatim: "i want a whole presentation dedicated to each challenge respetitcely ... fill with science and eng and everything", "u need to be quicker than that for present just be quick pls we have to do this 11 times", "i have 2 hours", "everuthing else except demo vids". So: one full presentation per Moth Hack 2026 challenge for "What the Noise Remembers" (22 playable quantum pieces on Moth Quantum's Atlas engines; one idea: a signal hides, gets lost in noise, and is rebuilt). SPEED MATTERS: read only what you need, write in one go, never render, screenshot or re-read your output.
FACTS: every number, name, job id, qubit count, parameter, backend and claim comes from the piece files (entries/<slug>/README.md, piece.json, PARAMS.md, CREDITS.md, ENGINES.md), ${ROOT}\\reference\\engines.txt (engine descriptions) and ${ROOT}\\cache\\jobs_index.json (every job: engine, qubits, target, reported_backends, piece). Never invent a statistic, quote or result. Simulator runs are simulator runs; call something real IBM hardware only if jobs_index shows a completed job reporting that ibm_ backend. No Moth Quantum logo.`

const LOOK = `SLIDE FORMAT (closed subset): fixed 1920x1080 canvas; one <section id="<id>" ...> per file and nothing else; every style inline; px units (width/height % only on pinned or flex children); NO margin, z-index, classes, <style>, var(). Section: background (always), font-family, color, display:flex (flex-direction:column) or display:grid, padding, gap, align-items, justify-content. Elements: h1 h2 h3 p (font-size always set, never under 24px), ul/ol of plain li, br, inline b i u a span(color only); div (flex row/column or grid; <=15 deep); img src alt style="width;height;object-fit:contain|cover"; table/tr/th/td (first row th, width:N% on every first-row cell, 24-28px); svg (no text); hr; x-shape kind="rect|rounded|ellipse|diamond|arrow-right|arrow-left|arrow-up|arrow-down|line"; x-icon name in (Activity Book Chart Chat Check CheckCircle Clock Cloud Code Database Globe GraduationCap Home Key Lightbulb Lightning Link Lock PaperPlane Play Search Settings Star ThumbsUp Tool Trust Users Verified Warning Wrench); x-connector (flow child between boxes: <x-connector style="width:96px"></x-connector>). position:absolute pins to the slide (left/top/width/height; pinned text needs width). <=200 elements per slide. Text wraps only at spaces (~0.6 x font-size per character). Room inside padding: 792px tall with the footer padding; split rather than shrink. Speaker notes: one <aside> of plain text (2-5 sentences) as the section's LAST child.
LOOK (match ${COVER} exactly; read it once): paper #FBFAF9 (main bg), panel #F0F0F4 (cards, second tone), ink #19238E (headings, strong, rules), ink-2 #545BA9 (body), rule #D3D3E6, accent #B4541A (mono eyebrows, odd highlighted figure), good #1F7A4D only with the words 'IBM hardware'. Fonts 'Geist', Arial, sans-serif and 'IBM Plex Mono', 'Courier New', monospace. Type scale ONLY 112/64/40/30/24. Pattern: mono 24px uppercase letter-spacing 2px #B4541A eyebrow, 64px ink heading at the top margin, content. Cards: #F0F0F4 or #FFFFFF, 1px solid #D3D3E6, border-radius 16px, padding 40px. Pills: mono 24px, 2px solid #19238E, radius 999px, padding 8px 20px. Big numbers: 112px Geist 500 ink + 24px mono label. Images object-fit:contain, 1px solid #D3D3E6 border. One statement slide per deck on #19238E with #FBFAF9 text (footer #A1A4CE).
FOOTER on every slide but the cover: section padding 128px 128px 160px; before the <aside>: <p style="position:absolute;left:128px;bottom:64px;width:1300px;font-family:'IBM Plex Mono', 'Courier New', monospace;font-size:24px;color:#545BA9">What the Noise Remembers · Challenge NN · NAME</p> and <p style="position:absolute;right:128px;bottom:64px;width:200px;text-align:right;font-family:'IBM Plex Mono', 'Courier New', monospace;font-size:24px;color:#545BA9">K / TOTAL</p>.`

const SETUP_OUT = {type:'object', properties:{deck_url:{type:'string'}, root:{type:'string'}, argsFile:{type:'string'}, total:{type:'number'}, groups:{type:'array', items:{type:'object', properties:{ids:{type:'array', items:{type:'string'}}}, required:['ids']}}}, required:['deck_url','root','argsFile','total','groups']}
const W_OUT = {type:'object', properties:{written:{type:'array', items:{type:'string'}}, notes:{type:'string'}}, required:['written','notes']}
const P_OUT = {type:'object', properties:{deck_url:{type:'string'}, slides:{type:'number'}, ok:{type:'boolean'}, notes:{type:'string'}}, required:['deck_url','slides','ok','notes']}

const setup = c => {
  const root = `${SCR}\\decks\\c${c.n}`
  return `${ASK}
YOUR CHALLENGE: Challenge ${c.n} · ${c.name}. Pieces: ${c.pieces.join(', ')} (in ${ROOT}\\entries\\).
TASK (setup only; other agents write most slides in parallel after you):
1. Skim each piece's README.md and piece.json (and PARAMS.md headline) to plan the deck. Look at candidate images (hero.png and figure PNGs in the piece folder and out/, docs\\demos\\<slug>.png page stills, entries/<slug>/qa/desktop.png 1280x900 page screenshots) with Read, quickly.
2. Copy 8-15 chosen images into ${ROOT}\\submission\\challenge-${c.n}\\deck_img\\ (downscale anything wider than 2000 px with Pillow; png/jpg/webp only; extract an MP4 frame with the ffmpeg from imageio_ffmpeg if needed).
3. Create the deck: Artifact publish with type_url "${SLIDES_TYPE}", title "Challenge ${c.n} · ${c.name}", auto_open "after_first_write", no files. Then upload the images: Artifact publish with url=<the new deck>, asset:true, file_paths=[the images]. Keep the returned /_blob/<id> urls.
4. Plan 18-24 slides with ids ([a-z0-9-]): cover; idea and challenge; a map of the pieces; THE ENGINE(S) EXPLAINED (what each Atlas engine used does, its parameters and qubit limits, simulator vs IBM hardware, a simple diagram); for EACH piece 3-5 slides: the science behind its subject (with the README's named sources), what you do on the page (screenshot, characters, which are data-driven), the engineering (scripts, parameters, how outputs are measured and replayed), the results (measured numbers, real output images), for pieces with IBM hardware runs a hardware slide (backend, qubits, job ids, what changed vs simulator); across the challenge (comparison); the statement slide; how the project is built (pipeline diagram: scripts -> cached Atlas client with job ledger, credit caps, freeze replay -> engines -> classical measurement -> build_web.py -> self-contained HTML/JS page -> headless-Chromium QA -> GitHub Pages); runs table (engine, qubits, simulator/IBM backend, jobs, credits per piece); key job ids; what this does not claim (piece.json honesty + README); credits and data licences; try it (live links ${SITE}pieces/<slug>/ for each piece, repo ${REPO}, and 'An independent entry to Moth Hack 2026, built on Moth Quantum's Atlas engines. Not an official Moth Quantum page.').
5. Write ${root}\\project\\deck.json: {"v":4,"createdOnFiles":{"v":1,"at":"2026-10-05T20:00:00Z"},"lists":"css","title":"Challenge ${c.n} · ${c.name}","order":[ALL ids],"sections":{...one per part, {"description":"<one sentence>","start":"<first id>"}},"faces":{"geist":{"family":"Geist","href":"https://fonts.googleapis.com/css2?family=Geist:wght@300..600&display=swap"},"ibm-plex-mono":{"family":"IBM Plex Mono","href":"https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap"}},"designSystems":[]}. Write ${root}\\project\\slides\\cover.html in the cover's exact style (read ${COVER}: eyebrow "Moth Hack 2026 · Challenge ${c.n}", the challenge name as the 112px title, a one-line subtitle, piece-title pills, one strong image), with an <aside>.
6. Publish both: Artifact publish with url=<deck>, root=${root}, file_path=${root}\\project\\deck.json, files={"project/slides/cover.html":"project/slides/cover.html"}.
7. Write ${root}\\args.json: {"cover": <the cover html>, "blobs": {"<file name>: <what it shows>, <w>x<h>": "/_blob/<id>", ...}, "groups": [{"ids": [...], "brief": "<for each id: what that slide shows, the exact facts/numbers to use with their source file, which image>"}, ...]} splitting ALL ids except cover into 3-4 groups of consecutive slides (about equal size). Make the briefs specific (numbers + sources) so writers need little reading.
${LOOK.replace(/NN/g, c.n).replace('NAME', c.name)}
Return deck_url, root (${root}), argsFile (${root}\\args.json), total slide count, and groups (ids only).`
}

const writer = (c, s, g) => `${ASK}
Challenge ${c.n} · ${c.name}; pieces ${c.pieces.join(', ')} (${ROOT}\\entries\\). FIRST read ${s.argsFile}: 'cover' is the cover slide's HTML (match its look exactly), 'blobs' maps uploaded images (description) to urls (use VERBATIM as src; no other images), 'groups' has the brief for your ids. Then read only the piece files you need and write your slides.
YOUR SLIDES: ${g.ids.join(', ')}. Write each to ${s.root}\\project\\slides\\<id>.html. Their positions: read 'order' in ${s.root}\\project\\deck.json (K = index + 1, TOTAL = ${s.total}).
${LOOK.replace(/NN/g, c.n).replace('NAME', c.name).replace('TOTAL', String(s.total))}
Do NOT publish. Return the files written.`

const publisher = (c, s) => `Publish the finished slides of the Challenge ${c.n} deck ${s.deck_url}. Folder: ${s.root}. List ${s.root}\\project\\slides\\*.html; every id in ${s.root}\\project\\deck.json 'order' should have a file (report any missing). Each file must hold exactly one <section id="<its id>">; if a file has text before or after the section, trim it. Then ONE Artifact call: publish with url=${s.deck_url}, root=${s.root}, file_path=<absolute path of one slide file other than cover.html>, files={"project/slides/<id>.html":"project/slides/<id>.html" for every other slide file except cover.html}. Do not send deck.json or cover.html (already published). If refused, follow the refusal once. Return deck_url, the slide count and ok.`

const out = await pipeline(args.challenges,
  c => agent(setup(c), {label:`setup:${c.n}`, phase:'Setup', schema: SETUP_OUT}),
  (s, c) => s ? parallel(s.groups.map(g => () => agent(writer(c, s, g), {label:`write:${c.n}:${g.ids[0]}`, phase:'Write', schema: W_OUT}))).then(w => ({s, w})) : null,
  (x, c) => x ? agent(publisher(c, x.s), {label:`publish:${c.n}`, phase:'Publish', schema: P_OUT, effort:'low'}) : null)
return out.map((p, i) => ({challenge: args.challenges[i].n, deck: p && p.deck_url, slides: p && p.slides, ok: p && p.ok, notes: p && p.notes}))
