export const meta = {
  name: 'challenge-decks',
  description: 'One presentation deck per Moth Hack challenge, plus a folder of form-ready images and form text, then an independent fact check',
  phases: [
    { title: 'Build', detail: 'deck + submission folder per challenge' },
    { title: 'Check', detail: 'every number and claim against the piece files; fix' },
  ],
}
const ROOT = 'C:\\Users\\Rahma\\OneDrive\\Desktop\\MOTH QUANTUM'
const SCRATCH = args.scratch
const SLIDES_TYPE = 'https://claude.ai/artifact/8jTsAFQMFDb2oA8MsPJ2eL'
const REPO = 'https://github.com/hrahman12/What-the-noise-remembers-MOTH-QUANTUM-HACK'
const SITE = 'https://what-the-noise-remembers.vercel.app/'
const ASK = `CONTEXT, the user's requests verbatim (most recent last): "give stuff for the images for challenge 01 to donwload straigjt here pls. make a presentation just for challenge 01", then "make a presntation for each 11 pls", then (latest, overriding) "just make presentation deck for the 1st challlenge". So only the Challenge 01 deck is wanted now. The user is filling in the Moth Hack 2026 submission form (Airtable), one submission per challenge. The form asks for: Project title, Elevator pitch (one sentence), Select your challenge, Project description (100-200 words: concept, artifacts produced, motivation), Technical description (50-100 words: tools and techniques, which Moth Atlas engines were used), Which Moth Atlas engines did you use (multi-select, e.g. "Blur engine", "Labyrinth engine", "Coin Toss engine", "Tessa Image engine", "Telablur engine", "Retrocausal Echo engine", "Entanglement Shader engine"), QPU or emulation (e.g. "Some emulation, some QPU."), Code repository, Demo URL, Generative AI usage, What generative AI tools did you use, and image uploads. The project is "What the Noise Remembers": 22 playable pieces for Moth Hack 2026 (Moth Quantum's Atlas engines), one idea across all: a signal hides, gets lost in noise, and is rebuilt. Judging is on quality of execution, depth of quantum and Atlas usage, and originality. This task is exactly what the user asked for: do it in full for this challenge.`

const DESIGN = `DECK LOOK (identical across all 11 decks, matching the project's Moth Hack paper-and-ink site):
- Typefaces: 'Geist' (headings and text, weights 300-600) and 'IBM Plex Mono' (eyebrows, labels, numbers, job ids). faces in project/deck.json: {"geist":{"family":"Geist","href":"https://fonts.googleapis.com/css2?family=Geist:wght@300..600&display=swap"},"ibm-plex-mono":{"family":"IBM Plex Mono","href":"https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap"}}. Stacks: 'Geist', Arial, sans-serif and 'IBM Plex Mono', 'Courier New', monospace.
- Colours: paper #FBFAF9 (main background), panel #F0F0F4 (second background tone, cards), ink #19238E (headings, rules, strong text), ink-2 #545BA9 (body text), rule #D3D3E6 (hairlines, 1-2px), accent #B4541A (mono eyebrows and the odd highlighted figure only), good #1F7A4D (only for a 'real hardware' marker, always with the words). One statement slide per deck on solid ink #19238E with #FBFAF9 text.
- Type scale: 112 / 64 / 40 / 30 / 24 px. Eyebrows: IBM Plex Mono 24px uppercase letter-spacing 2px in #B4541A. Hairline rules and pill labels (IBM Plex Mono 24px, 1.5px #19238E border, border-radius 999px, padding 8px 20px) echo the site.
- Footer on every slide except the cover: one pinned 24px IBM Plex Mono row at bottom:64px in #545BA9: "What the Noise Remembers · Challenge NN · <challenge name>" on the left and the slide number "NN / TT" on the right; such slides use padding:128px 128px 160px.
- Images: the project's own images only (listed below), uploaded as assets of this deck; engine outputs and charts use object-fit:contain on #F0F0F4 or #FBFAF9 with a 1px #D3D3E6 border; screenshots of the playable pages likewise. Never a stock photo.
- Never put the Moth Quantum logo or wordmark on a slide. The closing slide carries: "An independent entry to Moth Hack 2026, built on Moth Quantum's Atlas engines. Not an official Moth Quantum page."`

const OUTLINE = `DECK CONTENT (about 9-13 slides; one idea per slide; speaker notes in an <aside> on every slide, 2-5 sentences a presenter can say):
1. Cover: eyebrow "MOTH HACK 2026 · CHALLENGE NN", the challenge name as the title, "What the Noise Remembers" and the piece title(s) as a subtitle, one strong image from the piece(s).
2. The challenge and our answer: what this challenge category is (use only its name and how the pieces' own README/piece.json describe it; never invent rules or requirements of the official brief), and in one or two sentences how the piece(s) answer it.
3. For EACH piece in this challenge (2-3 slides each): (a) what you do on the page (the hook, the controls, the characters), with a screenshot; (b) the quantum part: the engine(s), qubits, parameters, what the engine did, with the real output image(s); (c) optional: the key result or measurement, as a big number or a small table.
4. Engines and runs: a table per piece or for the challenge: engine, qubits, simulator or IBM hardware (backend name), number of jobs, credits. Mark IBM hardware runs with the backend name (ibm_fez, ibm_marrakesh, ibm_miami) and the job ids where there are only a few. Use cache/jobs_index.json and the piece's piece.json/PARAMS.md/CREDITS.md for these numbers.
5. A statement slide (ink background) with the one-sentence idea of the challenge entry.
6. What this does not claim: the honesty notes from piece.json "honesty" and the README's "What this does not claim" section, verbatim or tightly paraphrased.
7. Try it: the live page link(s) ${SITE}pieces/<slug>/ and the repo ${REPO}, plus the independent-entry line.`

const DEEP = `FULL DEPTH (the user asked, verbatim: "i want a whole presentation dedicated to each challenge respetitcely give me the first one ... fill with science and eng and everything for ch 1"). This deck is the WHOLE story of the challenge entry, about 20-26 slides, organised into sections (deck.json "sections"):
A. Opening: cover; the one idea of the project (a signal hides, gets lost in noise, and is rebuilt) and how this challenge's pieces carry it; the challenge and our answer; a one-slide map of the pieces (cards with image, hook, engine, qubits, jobs).
B. The engine, explained: what the engine is and does, from ${ROOT}\\reference\\engines.txt (the engine's own description and params) and the pieces' READMEs/ENGINES.md: how an image becomes a quantum state, what the parameters do (for blur-v1: strength, style rx/ry, reach, size, mask), how the qubit count is set (for blur-v1: ceil(log2 w) + ceil(log2 h) on the mask's bounding box, 20 max), what runs where (Atlas statevector simulator vs IBM hardware), and what comes back. A simple diagram (div boxes + x-connector arrows) of input image + mask -> engine -> output. Cite the open-source origin if the README names it (e.g. QuantumBlur, qiskit-community).
C. One section per piece (4-6 slides each): (1) the science behind its subject, from its README "The science" section and named sources (e.g. Penrose tilings, aperiodic order, substitution/deflation and Li & Boyle's result that Penrose tilings are quantum error-correcting codes; MERFISH spatial transcriptomics, the mouse-brain dataset, what the chosen genes mark; virtual unwrapping of carbonised scrolls, Seales et al.), with the citation; (2) what you do on the page, with the page screenshot and the cast of characters and which of them are driven by data; (3) the engineering: how the inputs were made (scripts named), the mask, the parameter sweep design, how outputs are measured classically, how the page stores and replays the job outputs, shareable links; (4) the results: the measured numbers (e.g. % of hole pixels changed, agreement r, ghost signal, line kept r vs ink moved) as big numbers, a small table or a chart, with the real output images; (5) what it shows and does not show.
D. Across the challenge: what the same engine did to three very different images (a comparison slide); the statement slide (ink background).
E. Engineering of the whole project: the pipeline (cached Atlas client with a job ledger, per-piece credit caps and a freeze switch so builds replay recorded jobs; Python build scripts; self-contained HTML/JS pages; shared paper-and-ink look; pixel-art sprites; QA with headless Chromium: console errors, phone width, dead-control detector, end-to-end journeys; static export to GitHub Pages), drawn as a diagram, only as described in the repo files (common/BUILD_GUIDE.md, atlas/client.py, common/qa/*, README "How it's built").
F. Runs and honesty: the engines-and-runs table (jobs, credits, qubits, simulator/hardware), an appendix slide with the job ids of the key sweep(s) in a compact mono table, the "What this does not claim" slide, credits and data licences (e.g. MERFISH data CC BY 4.0, sources), and the closing "Try it" slide.
Keep one idea per slide and the type scale; split rather than shrink. Speaker notes on every slide.`

const FACTS = `FACTS RULE: every number, name, job id, qubit count, backend, credit count and claim on a slide or in the form text must come from the piece's files: entries/<slug>/README.md, piece.json, PARAMS.md, CREDITS.md, ENGINES.md if present, web/template.html, and ${ROOT}\\cache\\jobs_index.json / cache\\ledger.jsonl. Never invent a statistic, a quote or a result. If two files disagree, use the newer piece.json/README and say so in the notes. Label simulator runs as simulator runs; only call something "real IBM hardware" when jobs_index.json shows it ran on that backend and completed.`

const IMAGES = `IMAGES: the best visuals for this challenge are in entries/<slug>/ (hero.png, sweep/jobs/ladder/figure PNGs, out/*.png), docs\\demos\\<slug>.png (a still of the playable page), docs\\demos\\<slug>.gif and .mp4 (demo clips), and the web/img/ folders. Look at candidates with the Read tool before choosing. Prefer clear, striking images; avoid near-duplicates.`

const SUBMIT = (c) => `SUBMISSION FOLDER: create ${ROOT}\\submission\\challenge-${c.n}\\ (it may already exist for challenge 01: keep its files, add only what is missing) and copy into it, with clear names like <slug>_<what-it-shows>.png: 4-10 of the best images for this challenge (PNG or JPG, each under 5 MB; include each piece's docs\\demos\\<slug>.png page still and docs\\demos\\<slug>.gif demo clip if they exist), all ready to upload to the form. Then write ${ROOT}\\submission\\challenge-${c.n}\\FORM.md with ready-to-paste answers, each under its form field's name: Project title ("What the Noise Remembers: <piece titles>" or similar), Elevator pitch (ONE sentence, specific to this challenge's pieces), Select your challenge (the category name as the user will see it, e.g. "Beginner 1: One image, one engine" for 01; for others write the challenge number and name as in the README table and note that the user should pick the matching option), Project description (100-200 words, count them and state the count), Technical description (50-100 words, count them), Which Moth Atlas engines did you use (the engine names as the form likely shows them, e.g. blur-v1 = "Blur engine", plus the Atlas engine ids in brackets; ONLY engines this challenge's pieces actually used, from piece.json "engines"), QPU or emulation (choose honestly: emulation only, some QPU, or QPU, from jobs_index.json; name the IBM backends and job ids if any), Code repository (${REPO}), Demo URL (${SITE}pieces/<slug>/ for a one-piece challenge; for several pieces give the first piece's link and list the others), Generative AI usage (state plainly that the code, pages and text were written with Anthropic's Claude (Claude Code) under the author's direction, and that every quantum result comes from real Atlas jobs), What generative AI tools did you use ("Claude (Anthropic), via Claude Code"), and an "Images to upload" list of the files in the folder with one line each on what it shows.`

const build = (c) => `${ASK}

YOUR CHALLENGE: Challenge ${c.n} · ${c.name}. Pieces: ${c.pieces.join(', ')} (folders under ${ROOT}\\entries\\).
${c.deck ? `A deck for this challenge ALREADY EXISTS and is empty: ${c.deck}. Fill THAT deck (do not create another).` : `Create the deck: Artifact publish with type_url "${SLIDES_TYPE}", title "Challenge ${c.n} · ${c.name}", auto_open "after_first_write", and no files. Its reply carries the Slides type's full instructions: follow them exactly for the deck's files (project/deck.json first with the full order and faces, then the cover, then the other slides), uploads and calls. The account has no design system: use the look below, and skip any step about choosing one.`}
Work folder for the deck files: ${SCRATCH}\\decks\\c${c.n}\\ (use it as the Artifact call's root; put project/deck.json and project/slides/*.html under it). Upload images to the deck as assets (Artifact publish with url=<the deck>, asset:true, file_paths=[...] for up to 25 image files), and use each returned url verbatim in <img src>. Convert anything that is not png/jpg/gif/webp first (e.g. extract an MP4 frame with the ffmpeg from python -c "import imageio_ffmpeg;print(imageio_ffmpeg.get_ffmpeg_exe())"). Keep each uploaded image under 5 MB (downscale big PNGs to at most 2400 px wide with Pillow into your work folder).

${DESIGN}

${c.deep ? DEEP : OUTLINE}

${FACTS}

${IMAGES}

${SUBMIT(c)}

Do not edit anything under entries/, docs/, site/ or common/. Do not run git. Do not publish any other artifact.
Return: the deck url, the slide count, the submission folder path, the list of files in it, and the FORM.md text.`

const OUT = {type:'object', properties:{challenge:{type:'string'}, deck_url:{type:'string'}, slides:{type:'number'}, folder:{type:'string'}, files:{type:'array', items:{type:'string'}}, form_md:{type:'string'}, notes:{type:'string'}}, required:['challenge','deck_url','slides','folder','files','form_md','notes']}
const VERDICT = {type:'object', properties:{pass:{type:'boolean'}, fixed:{type:'array', items:{type:'string'}}, remaining:{type:'array', items:{type:'string'}}}, required:['pass','fixed','remaining']}

const check = (c, r) => `${ASK}

Independent fact check of the Challenge ${c.n} (${c.name}) deck and form text, pieces ${c.pieces.join(', ')} in ${ROOT}\\entries\\. Builder report: ${JSON.stringify(r)}.
Read the deck's slide files in ${SCRATCH}\\decks\\c${c.n}\\project\\ (deck.json and slides/*.html) and ${ROOT}\\submission\\challenge-${c.n}\\FORM.md. Check EVERY number, job id, qubit count, backend, engine name, credit count and claim against the piece files (README.md, piece.json, PARAMS.md, CREDITS.md) and ${ROOT}\\cache\\jobs_index.json. Also check: the word counts of Project description (100-200) and Technical description (50-100); the engines list contains only engines these pieces used; the QPU-or-emulation answer is honest (only completed IBM jobs count as hardware); the live links are ${SITE}pieces/<slug>/ for the right slugs; every slide has a footer except the cover; no Moth Quantum logo; the independent-entry line is on the last slide; every image file listed in FORM.md exists in the folder.
Fix what is wrong yourself: edit the slide files in that folder and republish ONLY the changed files to the deck (Artifact publish with url=${r && r.deck_url}, root=${SCRATCH}\\decks\\c${c.n}, file_path=<one changed file's absolute path>, files={<other changed files' project/... paths>: <same relative path>}; send project/deck.json only if you changed it), and edit FORM.md in place. Do not render or screenshot the deck. Return pass=true only if nothing wrong remains.`

const CH = args.challenges
const out = await pipeline(CH,
  c => agent(build(c), {label:`deck:${c.n}`, phase:'Build', schema: OUT}),
  (r, c) => r ? agent(check(c, r), {label:`check:${c.n}`, phase:'Check', schema: VERDICT}).then(v => ({r, v})) : null)
return out.map((x, i) => x ? {challenge: CH[i].n, deck: x.r.deck_url, slides: x.r.slides, folder: x.r.folder, files: x.r.files.length, check: x.v} : {challenge: CH[i].n, failed: true})
