export const meta = {
  name: 'realism-pass',
  description: 'Rework sprites in selected pieces into real-life, scientifically accurate depictions, then QA and judge',
  phases: [
    { title: 'Realism', detail: 'real-life sprites/illustrations per piece' },
    { title: 'Judge', detail: 'accuracy + QA + honesty' },
    { title: 'Fix', detail: 'address the judge, re-judge' },
  ],
}

const ROOT = 'C:\\Users\\Rahma\\OneDrive\\Desktop\\MOTH QUANTUM'
const BRIEF = {
 '03-moth-eye': 'A REAL moth compound eye: a realistic moth head in profile (scales, antennae, proboscis), zooming into the actual compound eye, its hexagonal ommatidia and the sub-wavelength corneal nipple array (nanopillars ~200 nm pitch) on each facet, with labelled callouts. The lamp and the watching bat can stay, but drawn realistically. Keep the three.js viewer and the honest reflectance result.',
 '07-flavour': 'REAL-LIFE neutrino physics objects as the main art: realistic sources (a nuclear reactor containment dome, the Sun, an accelerator beamline and target hall in the Fermilab style) and a realistic detector (a Super-Kamiokande-style cylindrical water tank lined with photomultiplier tubes, with a Cherenkov ring flashing when a neutrino of the chosen flavour interacts: electron-like fuzzy ring vs muon-like sharp ring, which is real detector physics). The journey map should show realistic baselines (reactor km, accelerator hundreds of km, Sun ~150 million km). The gelato/flavour pun may survive only as a small legend; the scene must read as real neutrino physics. Keep the synth, the real measured qpixl curves and the CHIP selector.',
 '08-pbit-or-qubit': 'USER ASKED TWICE: real-life hardware art AND \'GIVE ME THE P-BIT STUFF COOLER PLEASE\'. Keep Fire vs Ice but make it an ARCADE SHOWDOWN. A versus-screen intro (SAUNA vs FRIDGE, like a fighting-game title card); round-based play with a countdown per guess, streak multipliers and combo callouts; screen shake, steam particles for heat and frost particles for cold; Web Audio sound effects started by the player (sizzle vs crystalline chime, a satisfying hit on a correct guess); and a BOSS ROUND whose batches are the REAL ibm_fez hardware samples. Use real-life hardware art: a p-bit as an actual stochastic magnetic tunnel junction (free layer / MgO barrier / fixed layer nanopillar, fluctuating magnetisation, wires) or a thermodynamic chip at room temperature, vs a gold-plated dilution-refrigerator chandelier whose stages are labelled (roughly 50 K, 4 K, still, cold plate, mixing chamber at around 10-20 mK). Clearing levels takes the player DOWN the fridge stage by stage as a level map. The 20 Ising spins are a magnet board of arrows that flip with the REAL samples and click audibly. The coupling J is a dial. A live \'are you beating chance?\' meter gives an honest binomial p-value of the player\'s guesses: if the samplers really are hard to tell apart, the game says so, and that\'s part of the fun. Unlock short lab-fact cards. No quantum-advantage claims; emulator vs hardware clearly labelled; nothing autoplays; big tap targets on mobile. Mascot = the parka qubit or the sweating p-bit, drawn in the new style.',
 '10-squeezed-chirp': 'USER ASKED: make the LIGO project more GAME-LIKE, and use REAL-LIFE art. Turn the page into a game, working title LIGO NIGHT SHIFT: CATCH GW150914 (improve the name if you like). The player is the operator in a realistic LIGO control room on 14 Sep 2015, the night of the first detection (check the real date and time, and the event facts you quote, against LIGO/GWOSC sources: masses, distance, energy radiated). Real-life art: the actual L-shaped observatory (two 4 km arms at right angles, corner and end stations, arm tube), an optics cutaway (laser, beam splitter, Fabry-Perot arm mirrors, the squeezed-light source injecting at the output port), and realistic black holes (dark shadows with lensed photon rings) inspiralling and merging in sync with the real chirp time axis. GAME LOOP, one round at a time and started by the player: (1) SET THE SQUEEZER: a hardware-style dial picks one of the real cached blur-core-v1 outputs (the 5 constant-product ratios plus the isotropic control); (2) LISTEN: the detector plays the real resynthesised audio for that setting while the spectrogram scrolls in and the mirrors jitter with the strain; (3) TIMING CHALLENGE: hit a big MERGER! button at the chirp peak, scored against the true peak time, with a tolerance computed from that output\'s REAL measured time-width; (4) PITCH CHALLENGE: drag a marker to the chirp\'s peak frequency, with a tolerance from the REAL measured frequency-width. Because the blur keeps time-width x freq-width fixed, no setting can max both scores, so the game teaches the squeezing trade-off by feel. Add a score panel, a per-setting best (localStorage, wrapped in try/catch), a few achievements (for example a balanced \'Heisenberg\'s choice\'), an event-candidate alert card when you catch it, pause, replay and reset. Nothing autoplays; mobile gets big tap targets. Keep the honesty: the scores are a game built from real measured widths, and the per-axis blur is an ANALOGY to LIGO\'s squeezed light, not a simulation of it (keep the real-squeezing drawer: frequency-dependent squeezing, Ganapathy et al. PRX 2023). The notebook deliverable stays unchanged and is linked from the page. Mascot = a realistic LIGO L or the black-hole pair.',
 '12-chirp-instrument': 'REAL LIGO and black holes as the instrument stage: a realistic L-shaped observatory (Hanford or Livingston) and a realistic binary black hole pair (dark shadows with lensed rings) whose orbit tightens with the real chirp frequency track as notes play, plus the GW170817 neutron-star pair where used. Keep the playable instrument, the real blurred MIDI and honesty.',
 '14-hemibrain-ising': 'An anatomically REAL Drosophila melanogaster (correct proportions, compound eyes, ocelli, bristles, wing venation, halteres, six legs) and a realistic brain view behind the metro map: the real neuropils (mushroom bodies, central complex with ellipsoid body and fan-shaped body, antennal lobes, optic lobes) in a scientific-plate style, with the 20 real hemibrain neurons placed in or near the regions they actually belong to, using the data. Keep the metro/transit interaction, the two samplers and the honesty.',
}
const SLUGS = args.slugs
const OUT = {type:'object', properties:{slug:{type:'string'}, qa_ok:{type:'boolean'}, sound_ok:{type:'boolean'}, realistic:{type:'array', items:{type:'string'}}, issues_left:{type:'array', items:{type:'string'}}, summary:{type:'string'}}, required:['slug','qa_ok','sound_ok','realistic','issues_left','summary']}
const VERDICT = {type:'object', properties:{pass:{type:'boolean'}, realism_score:{type:'number', description:'1-5: accurate, real-life depiction of the actual objects?'}, fun_score:{type:'number'},
  issues:{type:'array', items:{type:'object', properties:{severity:{type:'string', enum:['blocking','minor']}, what:{type:'string'}, fix:{type:'string'}}, required:['severity','what','fix']}}, checked:{type:'string'}}, required:['pass','realism_score','fun_score','issues','checked']}
const port = i => 5700 + i * 20
const REQUESTS = "AUTHORISATION AND CONTEXT: this task comes from the lead agent acting on the user's explicit requests in this session. The user's messages, verbatim and in order: (1) 'please make ligo sprites, black hole pbit make the moth eye real eye. make the sprites real life flavor challenge sprites fly brain sprite'; (2) 'can we make the ligo project better somehow more game like?'; (3) 'GIVE ME THE P-BIT STUFF COOLER PLEASE'. Request (1) covers pieces 03 (moth eye), 07 (FLAVOUR), 08 (p-bit), 10 and 12 (LIGO/black holes) and 14 (fly brain). Request (2) is piece 10, and request (3) is piece 08. The latest chat message is NOT the whole scope: do the brief below in full."
const work = (s, i) => `${REQUESTS}
You are a scientific illustrator and front-end developer. Project root: ${ROOT}. Piece: entries/${s} (Moth Hack 2026, "What the Noise Remembers").
The user said: "make the sprites real life" for this piece. READ ${ROOT}\\common\\SPRITES.md (especially the "Realism pass" section at the end), ${ROOT}\\common\\BUILD_GUIDE.md section 4, and the piece's current web/template.html, web/sprites.json, build_web.py and README. A sprite pass already gave it cartoon characters: now make the subject matter REAL. An earlier attempt at this pass was interrupted part-way: inspect the folder's current state (template, sprites.json, build output), keep anything good, and finish the job; the built page must rebuild cleanly from source.
Brief: ${BRIEF[s]}
Use WebSearch/WebFetch to check what the real objects look like and how they're built (descriptions, dimensions, part names). Draw your own original art; don't embed or trace photos. Use higher-resolution pixel art and/or detailed SVG ink engravings in the shared palette, with labelled parts. Keep everything bound to the real cached data; keep the honesty labels; no new Atlas jobs (MOTH_FREEZE=1); audio still plays on the page with play/stop; nothing autoplays. Update the mascot (common/mascot.py -> web/img/mascot.png) to a realistic version of the subject, update CREDITS.md for any reference sources consulted, rebuild, and run node common/qa/qa_page.cjs entries/${s} ${port(i)} until ok. READ the screenshots and make it look accurate and beautiful at desktop and phone width. Return the structured result.`
const judge = (s, i, r) => `${REQUESTS}
Independent judge for entries/${s} in ${ROOT}. Judge the work against the brief, not against scope. The user asked for REAL-LIFE, scientifically accurate sprites. Brief: ${BRIEF[s]}. Builder report: ${JSON.stringify(r)}.
Run node common/qa/qa_page.cjs entries/${s} ${port(i) + 10}, read qa/report.json, and READ the three screenshots. Use WebSearch to check accuracy where unsure. Score realism_score 1-5 (are the actual objects depicted accurately and recognisably, with labels?) and fun_score 1-5. Blocking if: QA not ok, audio broken, the art still reads as generic cartoons, clear scientific inaccuracies, honesty lost, broken UI, or realism_score < 4. Don't submit Atlas jobs.`
const fix = (s, i, v) => `${REQUESTS}
Continue the realism work on entries/${s} in ${ROOT} (read common/SPRITES.md "Realism pass"). Brief: ${BRIEF[s]}. The judge found: ${JSON.stringify(v, null, 1)}. Fix the blocking issues and raise realism. No new Atlas jobs (MOTH_FREEZE=1). Rebuild, run node common/qa/qa_page.cjs entries/${s} ${port(i)} until ok, read the screenshots, and return the structured result.`

const out = await pipeline(SLUGS,
  (s, _o, i) => agent(work(s, i), {label:`real:${s}`, phase:'Realism', schema: OUT}),
  (r, s, i) => r ? agent(judge(s, i, r), {label:`judge:${s}`, phase:'Judge', schema: VERDICT, effort:'high'}).then(v => ({r, v})) : null,
  async (rv, s, i) => {
    if (!rv) return {slug:s, ok:false}
    if (rv.v && rv.v.pass) return {slug:s, ok:true, realism:rv.v.realism_score, fun:rv.v.fun_score}
    const f = await agent(fix(s, i, rv.v), {label:`fix:${s}`, phase:'Fix', schema: OUT})
    const v2 = f ? await agent(judge(s, i, f), {label:`rejudge:${s}`, phase:'Fix', schema: VERDICT, effort:'high'}) : null
    return {slug:s, ok:!!(v2 && v2.pass), realism:v2 && v2.realism_score, fun:v2 && v2.fun_score, open:v2 ? v2.issues.filter(x=>x.severity==='blocking').map(x=>x.what) : ['no re-judge']}
  })
return out